# 运行环境配置
server:
  port: 9000
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 300
    min-spare-threads: 65

spring:
  profiles:
    active: "@activatedProperties@"

logging:
  config: classpath:logback-spring.xml

