spring:
  datasource:
    druid:
      stat:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/nacos?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: root
        password: 123456
        max-active: 50
        initial-size: 10
        max-wait: 60000
        max-idle: 20
        min-idle: 10
        validation-query: select 1
        test-while-idle: true
        test-on-borrow: false # 获取链接时检查是否有效
        test-on-return: false # 归还链接时检查是否有效
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
  redis:
    host: 127.0.0.1
    database: 0
    password:
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: -1
        min-idle: 0
    timeout: 0
dubbo:
  register: 127.0.0.1:2181
  group:
    demo: demo-dev
